services:
  - type: web
    name: reflections-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
  - type: static
    name: reflections-web-render
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URLS
        sync: false
      - key: REACT_APP_WEATHER_API_KEY
        sync: false
